import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,useMotionValue,useSpring,useTransform} from 'framer-motion';
import { ArrowUpRight, CalendarDays, ChevronDown, Clock3, Camera, MapPin, Menu as MenuIcon, Phone, Send, X, Users, Navigation } from 'lucide-react';

import './styles.css';

const menu={
  COFFEE:[['MONA LATTE','Эспрессо, молоко, ванильная крема','390 ₽','☕'],['BLACK HONEY','Эспрессо, мёд, апельсин','420 ₽','◒'],['PISTACHIO CLOUD','Фисташковый крем, эспрессо, молоко','450 ₽','✦']],
  SIGNATURE:[['ORBIT ESPRESSO','Эспрессо, тоник, грейпфрут','430 ₽','◌'],['CARAMEL NOIR','Кофе, солёная карамель, сливки','460 ₽','◉'],['MONA TONIC','Колд-брю, цитрус, тоник','440 ₽','○']],
  DESSERTS:[['BROWNIE 01','Тёмный шоколад, морская соль','360 ₽','▰'],['PISTACHIO MOON','Фисташка, крем, малина','410 ₽','●'],['CLOUD CHEESE','Сливочный крем, ваниль, крошка','390 ₽','◍']],
  BREAKFAST:[['MONA TOAST','Бриошь, авокадо, яйцо, зелень','520 ₽','△'],['MORNING BOWL','Йогурт, гранола, ягоды','450 ₽','◒'],['EGG CLUB','Яйцо, сыр, соус, хрустящий хлеб','490 ₽','□']]
};

function Reveal({children,className=''}){return <motion.div className={className} initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.8,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function Navbar({open,setOpen}){return <header className="nav"><a className="brand" href="#top">МОНА<span>&</span>КО</a><nav><a href="#menu">МЕНЮ</a><a href="#contact">КОНТАКТЫ</a></nav><button className="reserve-pill" onClick={()=>document.querySelector('#booking')?.scrollIntoView({behavior:'smooth'})}>ЗАБРОНИРОВАТЬ <ArrowUpRight size={16}/></button><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<MenuIcon/>}</button>{open&&<motion.div className="mobile-drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}}><a href="#menu" onClick={()=>setOpen(false)}>МЕНЮ</a><a href="#philosophy" onClick={()=>setOpen(false)}>ФИЛОСОФИЯ</a><a href="#booking" onClick={()=>setOpen(false)}>БРОНЬ</a><a href="#contact" onClick={()=>setOpen(false)}>КОНТАКТЫ</a></motion.div>}</header>}
function Cursor(){const x=useMotionValue(-100),y=useMotionValue(-100),sx=useSpring(x,{stiffness:500,damping:40}),sy=useSpring(y,{stiffness:500,damping:40});const [label,setLabel]=useState('');useEffect(()=>{const move=e=>{x.set(e.clientX);y.set(e.clientY)};const over=e=>{const el=e.target.closest('[data-cursor]');setLabel(el?.dataset.cursor||'')};window.addEventListener('pointermove',move);window.addEventListener('pointerover',over);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerover',over)}},[]);return <motion.div className={'cursor '+(label?'active':'')} style={{left:sx,top:sy}}>{label}</motion.div>}
function Hero(){const [mouse,setMouse]=useState({x:0,y:0});return <section id="top" className="hero" onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();setMouse({x:(e.clientX-r.left-r.width/2)/r.width,y:(e.clientY-r.top-r.height/2)/r.height})}}><div className="hero-grid"/><div className="hero-meta"><span>EST. 2026</span><span>КРАСНОДАР / 45°02'N</span></div><motion.div className="hero-copy" animate={{x:mouse.x*8,y:mouse.y*8}}><p className="eyebrow">COFFEE CULTURE / DIGITAL ATELIER</p><h1>МОНА<span>&</span>КО</h1><p>Кофейня, в которую заходят за кофе,<br/>а остаются за атмосферой.</p></motion.div><motion.div className="coffee-orb" animate={{x:mouse.x*-24,y:mouse.y*-24,rotate:mouse.x*4}} transition={{type:'spring',stiffness:50,damping:14}}><div className="cup-glow"/><div className="cup"><div className="coffee-surface"><i/></div><div className="cup-body"><b>М</b><span>MONA&KO</span></div><div className="handle"/></div></motion.div><motion.div className="hero-bottom"><span>Кофе. Выпечка. Тепло.</span><span className="scroll">SCROLL ↓</span></motion.div></section>}
function Marquee({reverse=false}){return <div className={'marquee '+(reverse?'reverse':'')}><div>COFFEE — PEOPLE — MUSIC — MOMENTS — MONA&КО — COFFEE — PEOPLE — MUSIC — MOMENTS —</div></div>}
function Menu(){const [cat,setCat]=useState('COFFEE');return <section id="menu" className="menu-section"><Reveal><div className="section-head"><div><span className="eyebrow">01 / MENU</span><h2>Выбери<br/><em>своё.</em></h2></div><p>Меню меняется вместе с настроением. Чистые вкусы, неожиданные сочетания и никакой случайности.</p></div></Reveal><div className="cat-row">{Object.keys(menu).map(c=><button key={c} className={cat===c?'selected':''} onClick={()=>setCat(c)}>{c}</button>)}</div><motion.div layout className="menu-stage">{menu[cat].map(([name,desc,price,symbol],i)=><motion.article layout key={name} className="menu-item" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:i*.07}} data-cursor="VIEW"><div className="dish-art"><span>{symbol}</span><i/></div><div className="dish-info"><span className="index">0{i+1}</span><div><h3>{name}</h3><p>{desc}</p></div><strong>{price}</strong></div></motion.article>)}</motion.div></section>}
function Philosophy(){return <section id="philosophy" className="philosophy"><Reveal><span className="eyebrow">02 / ATTITUDE</span><h2>НЕ ПРОСТО<br/><span>КОФЕ.</span></h2><p>Мы любим хороший кофе, красивые места и разговоры, которые внезапно длятся три часа.</p></Reveal><div className="philosophy-mark">M<span>&</span>K</div></section>}
function Atmosphere(){return <section className="atmosphere"><Reveal><div className="atmo-card atmo-one"><div className="noise"/><span>01 — MORNING</span><b>Тихий свет.<br/>Первый глоток.</b></div></Reveal><Reveal><div className="atmo-card atmo-two"><span>02 — AFTERNOON</span><b>Город шумит.<br/>Мы — нет.</b></div></Reveal><Reveal><div className="atmo-card atmo-three"><span>03 — NIGHT</span><b>Музыка громче.<br/>Разговоры дольше.</b></div></Reveal></section>}
function Booking(){const [sent,setSent]=useState(false);const submit=e=>{e.preventDefault();setSent(true)};return <section id="booking" className="booking"><div className="booking-title"><span className="eyebrow">03 / RESERVATION</span><h2>ЗАБРОНИРОВАТЬ<br/><em>СТОЛ</em></h2></div><div className="booking-panel">{sent?<motion.div className="success" initial={{opacity:0,scale:.95}} animate={{opacity:1,scale:1}}><span>✓</span><h3>Место за вами.</h3><p>До встречи в Мона&Ко.</p><button onClick={()=>setSent(false)}>НОВАЯ БРОНЬ</button></motion.div>:<form onSubmit={submit}><label>ИМЯ<input required placeholder="Ваше имя"/></label><div className="two"><label>ДАТА<input required type="date"/></label><label>ВРЕМЯ<input required type="time"/></label></div><div className="two"><label>ГОСТИ<input required type="number" min="1" max="12" placeholder="2"/></label><label>ТЕЛЕФОН<input required type="tel" placeholder="+7 ___ ___ __ __"/></label></div><button className="submit" type="submit">ЗАБРОНИРОВАТЬ <ArrowUpRight/></button></form>}</div></section>}
function Location(){return <section id="contact" className="location"><div className="map-art"><div className="map-lines"/><div className="pin"><MapPin/></div><span>45.0228° N<br/>38.9700° E</span></div><div className="location-copy"><span className="eyebrow">04 / FIND US</span><h2>МОНА<span>&</span>КО</h2><p className="address">ул. Домбайская 55к7</p><div className="hours"><span><Clock3/> ПН–ПТ</span><b>09:00–21:00</b><span><Clock3/> СБ–ВС</span><b>09:00–21:00</b></div><a className="route" href="https://yandex.ru/maps/?text=ул.%20Домбайская%2055к7" target="_blank" rel="noreferrer" data-cursor="OPEN">ПОСТРОИТЬ МАРШРУТ <Navigation/></a><a className="phone" href="tel:+70000000000"><Phone/> +7 ХХХ ХХХ ХХ ХХ</a></div></section>}
function Footer(){return <footer><div className="footer-big">МОНА<span>&</span>КО</div><div className="footer-row"><p>Кофе, который<br/>остаётся с вами.</p><div className="socials"><a href="#">Camera</a><a href="#">Telegram</a><a href="#">VK</a></div><span>© {new Date().getFullYear()} MONA&KO</span></div></footer>}
function App(){const [open,setOpen]=useState(false);useEffect(()=>{const pre=document.querySelector('.preloader');const t=setTimeout(()=>pre?.classList.add('done'),1500);return()=>clearTimeout(t)},[]);return <><div className="preloader"><div className="pre-dot"/><div className="pre-line"/><div className="pre-logo">МОНА<span>&</span>КО</div></div><Cursor/><Navbar open={open} setOpen={setOpen}/><main><Hero/><Marquee/><Menu/><Philosophy/><Marquee reverse/><Atmosphere/><Booking/><Location/></main><Footer/></>}
createRoot(document.getElementById('root')).render(<App/>);
